### ISSUE TITLE
Statement of contributions

### ISSUE THREAD

**Issue by weerox** [will-berg/assignment1#28]
Part of the assignment is to include a statement of contributions in the README.

**Comment by filippaleuckfeld** [comment]
My statement of contributions: 
I have mainly worked on tests, setting up the unit test suite and tests for LIC 2, 9 and 12.

**Comment by weerox** [comment]
Mostly contributed to unit tests and the integration test and fixed some small bugs.

**Comment by ElHachem02** [comment]
Mainly worked on implementing some conditions, as well as writing unit tests and debugging conditions that failed the unit tests.

**Comment by salome-voltz** [comment]
My statement of contributions:
I have set up the unit test suite and tests for LIC 3, 4, 7, 10, 11. I have also fixed some small bugs and work on the report.

**Comment by will-berg** [comment]
Implemented some of the LIC conditions, wrote logic and control flow for the main program, and created relevant declarations.
